version: '3.4'

services:
  microserviceedudocumentgenerator:
    image: microserviceedudocumentgenerator:dev
    container_name: MicroServiceEduDocumentGenerator
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "MicroServiceEduDocumentGenerator"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_microserviceedudocumentgenerator$
    volumes:
      - C:\Udv\AAA Microservices\Microservices\MicroServiceEduDocumentGenerator\MicroServiceEduDocumentGenerator:/app
      - C:\Udv\AAA Microservices\Microservices\MicroServiceEduDocumentGenerator\.:/src
      - C:\Users\mri\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_microserviceedudocumentgenerator$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_microserviceedudocumentgenerator$ \"/app/bin/Debug/net5.0/MicroServiceEduDocumentGenerator.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true